REM INSERTING into TDF_ABANDON
SET DEFINE OFF;
Insert into TDF_ABANDON (ANNEE,N_ETAPE,N_COMP,N_COUREUR,C_TYPEABAN,COMPTE_ORACLE,DATE_INSERT,COMMENTAIRE) values ('1992','14',' ','1341','HC','ERIC',to_date('12/07/16','DD/MM/RR'),'s''est laiss� tract� par une voiture ');
Insert into TDF_ABANDON (ANNEE,N_ETAPE,N_COMP,N_COUREUR,C_TYPEABAN,COMPTE_ORACLE,DATE_INSERT,COMMENTAIRE) values ('1998','7',' ','92','EX',null,null,'Affaire Festina');
Insert into TDF_ABANDON (ANNEE,N_ETAPE,N_COMP,N_COUREUR,C_TYPEABAN,COMPTE_ORACLE,DATE_INSERT,COMMENTAIRE) values ('1998','7',' ','95','EX',null,null,'Affaire Festina');
REM INSERTING into TDF_ANNEE
SET DEFINE OFF;
Insert into TDF_ANNEE (ANNEE,JOUR_REPOS,COMPTE_ORACLE,DATE_INSERT) values ('1980','2','ERIC                ',to_date('05/07/20','DD/MM/RR'));
Insert into TDF_ANNEE (ANNEE,JOUR_REPOS,COMPTE_ORACLE,DATE_INSERT) values ('1982','2','ERIC                ',to_date('09/05/20','DD/MM/RR'));
